WebUI/Models/BooksListViewModel.cs
using ClassLibrary.Entities;
using System.Collections.Generic;

namespace WebUI.Models
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> Books { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentGenre { get; set; }
    }
}

WebUI/Models/CartIndexViewModel.cs
using ClassLibrary.Entities;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
    }
}

WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }     // Numbers of all books
        public int ItemsPerPage { get; set; }   // Numbers books per one page
        public int CurrentPage { get; set; }    // Current page number
        public int TotalPages 
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

WebUI/Controllers/AdminController.cs
using ClassLibrary.Abstract;
using ClassLibrary.Concrete;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace WebUI.Controllers
{
    //doesn't work
    public class AdminController : Controller
    {
        private IBookRepository _repository;

        public AdminController()
        {
            _repository = new EFBookRepository();
        }

        //public JsonResult ShowBooks()
        //{
        //    return Json(_repository.Books, JsonRequestBehavior.AllowGet);
        //}
    }
}

WebUI/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClassLibrary.Abstract;
using WebUI.Models;
using ClassLibrary.Concrete;

namespace WebUI.Controllers
{
    public class BooksController : Controller
    {
        private IBookRepository _repository;
        public int pageSize = 4;// Number of books per page
        
        public BooksController()
        {
            _repository = new EFBookRepository();
        }

        public ViewResult List(string genre, int page = 1)
        {
            BooksListViewModel model = new BooksListViewModel
            {
                Books = _repository.Books
                .Where(b => genre == null || b.Genre == genre)
                .OrderBy(book => book.BookId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = genre == null ?
                        _repository.Books.Count() :
                        _repository.Books.Where(book => book.Genre == genre).Count()
                },
                CurrentGenre = genre
            };

            return View(model);
        }
    }
}

WebUI/Controllers/CartController.cs
using ClassLibrary.Abstract;
using ClassLibrary.Concrete;
using ClassLibrary.Entities;
using WebUI.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;


        public CartController()
        {
            repository = new EFBookRepository();
        }

        public ViewResult Index(Cart cart)
        {
            return View(
                new CartIndexViewModel { Cart = cart }
                );
        }

        public RedirectToRouteResult AddToCart(Cart cart, int bookId)
        {
            Book book = repository.Books
                .FirstOrDefault(b => b.BookId == bookId);

            if (book != null)
            {
                cart.AddItem(book, 1);
            }

            return RedirectToAction("List","Books", new { genre = book.Genre});
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int bookId)
        {
            Book book = repository.Books
                .FirstOrDefault(b => b.BookId == bookId);

            if (book != null)
            {
                cart.RemoveLine(book);
            }

            return RedirectToAction("Index");
        }

    }
}

WebUI/Controllers/NavController.cs
using ClassLibrary.Abstract;
using ClassLibrary.Concrete;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController()
        {
            repository = new EFBookRepository();
        }

        public PartialViewResult Categories(string genre = null)
        {
            ViewBag.SelectedGenre = genre;

            IEnumerable<string> genres = repository.Books
                .Select(book => book.Genre)
                .Distinct()
                .OrderBy(x => x);

            return PartialView("Categories", genres);
        }
    }
}

WebUI/Views/Admin/ShowBooks.cshtml
@model IEnumerable<ClassLibrary.Entities.Book>
@using Newtonsoft.Json

@{
    /**/

    ViewBag.Title = "ShowBooks";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@Html.Raw(JsonConvert.SerializeObject(@Model))

<h2>ShowBooks</h2>

@*@section scripts {
    <script type="text / javascript">
        $(function() {
        $.get ('/Admin/' ).done ( function (cars) {
        $.each (cars, function (i, car)) {
        var item = '<li>
            <strong> $ {car.make} $ {car.model} </strong>
                (£ $ {car.price})</li>';
                $ ( '# car-list' ).append(item); });});
                });
    </script>
}
<script type="text/javascript">
        function OnSuccess(data) {
            var results = $('#BooksTable'); // получаем нужный элемент
            results.empty(); //очищаем элемент
            for (var i = 0; i < data.length; i++) {
                results.append('<li>' + data[i].Name + '</li>'); // добавляем данные в список
            }
        }
<div id="results"></div>
</script>*@


WebUI/Views/Books/List.cshtml
@using WebUI.Models
@using WebUI.HtmlHelpers
@model BooksListViewModel

@{
    ViewBag.Title = "Книги";
}

@foreach (var book in Model.Books)
{
    @Html.Partial("_BookSummary", book)
}

<div class="btn-group pull-sm-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, genre = Model.CurrentGenre }))
</div>


WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel
@{
    ViewBag.Title = "Ваша корзина";
}

<h2>@ViewBag.Title</h2>

<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Количество</th>
            <th>Наименование</th>
            <th class="text-right">Цена</th>
            <th class="text-right">Сумма</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Book.Name - @line.Book.Author</td>
                <td class="text-right">@line.Book.Price.ToString("# грн")</td>
                <td class="text-right">@((line.Quantity * line.Book.Price).ToString("# грн"))</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("BookId", line.Book.BookId)
                        <input class="btn btn-sm btn-warning" type="submit" value="Удалить" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# грн")
            </td>
        </tr>
    </tfoot>
</table>


WebUI/Views/Nav/Categories.cshtml
@model IEnumerable<string>

 @* Display all categories and create links to them*@

<div>
    @Html.ActionLink("Домой", "List", "Books", null, new {@class = " borderbtn btn btn-block btn-default btn-lg " })

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
        {
            controller = "Books",
            action = "List",
            genre = link,
            page = 1
        }, new
        {
            @class = " borderbtn btn btn-block btn-default btn-lg" + 
            (link == ViewBag.SelectedGenre ? " btn-primary" : "")
        })
    }
</div>

WebUI/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-reboot.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_BookSummary.cshtml
@model ClassLibrary.Entities.Book
<div class=" borderbtn well">
    <div class="row">
        <div class="col-xs-8">
            <h3>
                <strong>@Model.Name</strong>
            </h3>
            <h4>
                <strong>@Model.Author</strong>
            </h4>
        </div>
        <div class="col-xs-3">
            <h3>
                <strong id="price" class="pull-right label label-primary">
                    @Model.Price.ToString("# грн")
                </strong>
            </h3>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-sm-right">
                    @Html.HiddenFor(x => x.BookId)
                    <input type="submit" class="btn btn-success" value="В корзину" />
                </div>
            }
        </div>
    </div>
    <span class="lead">@Model.Description</span>
</div>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-reboot.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        @* tried show all books deserialized from Json. status: doesn't work*@
        @*@using (Ajax.BeginForm("ShowBooks", "Admin", new AjaxOptions { OnSuccess = "OnSuccess" }))
        {
            <input type="submit" value="All Books" />
        }*@
        <div class="navbar-right hidden-xs">
            @Html.ActionLink("Корзина", "Index", "Cart", null,
            new { @class = "btn btn-default navbar-btn" })
        </div>
    </div>

    <div class="row panel">
        <div id="genres" class="col-sm-3 hidden-xs">
            @Html.Action("Categories", "Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>